import{a as p,S as g,i as n}from"./assets/vendor-BAQQTdrx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const L="55711425-81a79a69bf21710388fc7a222",w="https://pixabay.com/api/";async function v(r,t){const o={key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await p.get(w,{params:o})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),b=new g(".gallery a");function S(r){const t=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),b.refresh()}function q(){f.innerHTML=""}function B(){m.classList.remove("hidden")}function $(){m.classList.add("hidden")}function M(){h.classList.remove("hidden")}function a(){h.classList.add("hidden")}const O=document.querySelector(".form"),P=document.querySelector(".load-more");let d="",i=1,u=0;O.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.elements.searchQuery.value.trim(),!d){n.error({message:"Please enter a search term!"});return}q(),a(),i=1,await y()});P.addEventListener("click",async()=>{a(),i+=1,await y(!0)});async function y(r=!1){try{B();const t=await v(d,i);if(t.hits.length===0){r?(n.info({message:"We're sorry, but you've reached the end of search results."}),a()):n.warning({message:"No images found!"});return}S(t.hits),u=t.totalHits,i*15>=u?(a(),n.info({message:"We're sorry, but you've reached the end of search results."})):M(),r&&E()}catch(t){n.error({message:"Something went wrong!"}),console.error(t)}finally{$()}}function E(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
