import{a as y,S as g,i as n}from"./assets/vendor-BAQQTdrx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const L="55711425-81a79a69bf21710388fc7a222",w="https://pixabay.com/api/";async function v(r,t){const o={key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await y.get(w,{params:o})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),b=new g(".gallery a");function S(r){const t=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",t),b.refresh()}function q(){u.innerHTML=""}function B(){f.classList.remove("hidden")}function $(){f.classList.add("hidden")}function M(){m.classList.remove("hidden")}function h(){m.classList.add("hidden")}const O=document.querySelector("#search-form"),P=document.querySelector(".load-more");let l="",a=1,d=0;O.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.searchQuery.value.trim(),!l){n.error({message:"Please enter a search term!"});return}q(),h(),a=1,await p()});P.addEventListener("click",async()=>{a+=1,await p(!0)});async function p(r=!1){try{B();const t=await v(l,a);if(t.hits.length===0){n.warning({message:"No images found!"});return}S(t.hits),d=t.totalHits,a*15>=d?(h(),n.info({message:"We're sorry, but you've reached the end of search results."})):M(),r&&E()}catch{n.error({message:"Something went wrong!"})}finally{$()}}function E(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
